### ISSUE TITLE
可以给我一下你的联系方式吗，有些问题想请教一下

### ISSUE THREAD

**Issue by ZizhuoLi** [huangyxi/WHUT-Bachelor#1]
**Describe the bug**

**Minimum Working Example**
A minimum example code that can reproduce the behavior.
The overall code should generally not exceed 10 lines.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10, macOS Catalina]
 - TeX Distribution [e.g. TeX Live 2019, MiKTeX 2.9.7152, Overleaf]
 - Application(s) [xelatex, latexmk, biber]
 - Editor [e.g. Texmaker, WinEdt]

**Additional context**

**Comment by huangyxi** [comment]
私下问题已解决，issue先关了，如果还有问题可以按照issue模板另开新issue。
