### ISSUE TITLE
学长，请问为什么把字体加进项目文件后，还是无法显示华文中宋字体啊。

### ISSUE THREAD

**Issue by nonholonomic** [huangyxi/WHUT-Bachelor#4]
**Describe the bug**

**Minimum Working Example**
A minimum example code that can reproduce the behavior.
The overall code should generally not exceed 10 lines.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10, macOS Catalina]
 - TeX Distribution [e.g. TeX Live 2019, MiKTeX 2.9.7152, Overleaf]
 - Application(s) [xelatex, latexmk, biber]
 - Editor [e.g. Texmaker, WinEdt]

**Additional context**

**Comment by huangyxi** [comment]
> 如果需要在缺省华文中宋的环境下使用该字体，请在获取字体版权方授权的前提下，将字体命名为`STZhongsong.ttf`，并放置在项目根目录(`./`)。

本人目前在Windows 11，TeX Live 2022使用xelatex编译能够正常显示*华文中宋*字体，在Adobe Acrobat下也能正常回报字体名，不太清楚阁下那边使用的是哪个LaTeX的平台。
如果不清楚需要提交哪些信息，可以修改按照issue提交模板修改，也就是[阁下发的信息](https://github.com/huangyxi/WHUT-Bachelor/issues/4#issue-1206965975)。
另外要注意，根据2020年的要求（也就是本人自己实际使用模板那年的要求），只有封面的字体为*华文中宋*，如果要求有更新可以另外提出来。

**Comment by nonholonomic** [comment]
我是在win10，TeX Live 2022使用xelatex编译，但是标题还是无法显示华文中宋字体，是要更新到win11吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangyxi/WHUT-Bachelor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huangyxi/WHUT-Bachelor] 学长，请问为什么把字体加进项目文件后，还是无法显示华文中宋字体啊。 (Issue #4)





  
如果需要在缺省华文中宋的环境下使用该字体，请在获取字体版权方授权的前提下，将字体命名为STZhongsong.ttf，并放置在项目根目录(./)。
  
本人目前在Windows 11，TeX Live 2022使用xelatex编译能够正常显示华文中宋字体，在Adobe Acrobat下也能正常回报字体名，不太清楚阁下那边使用的是哪个LaTeX的平台。
 如果不清楚需要提交哪些信息，可以修改按照issue提交模板修改，也就是阁下发的信息。
 另外要注意，根据2020年的要求（也就是本人自己实际使用模板那年的要求），只有封面的字体为华文中宋，如果要求有更新可以另外提出来。

**Comment by huangyxi** [comment]
虽然系统版本原因的可能性极小，而且在系统升级前我也能正常输出华文中宋字体，不过由于我手边没有Windows 10的设备，当然也不能排除这个原因。
但是我还是希望阁下能提供更多**能复现该问题**的信息，也就是issue提交模板即[阁下发的信息](https://github.com/huangyxi/WHUT-Bachelor/issues/4#issue-1206965975)中推荐提交的6个部分。
关键是阁下是从clone或下载，到输出最终文件一共经过了哪些（关键）操作，例如是否有按照[README文件](https://github.com/huangyxi/WHUT-Bachelor/blob/f84e8e108dd1315f519065fa7e33acd7b9b370e6/README.md)和[回复引用](https://github.com/huangyxi/WHUT-Bachelor/issues/4#issuecomment-1101956791)提及的重命名字体文件名，修改了源文件哪些代码，最小能复现问题的代码（Minimum Working Example，MWE）等等。

**Comment by nonholonomic** [comment]
下载文件后用bindzip解压开，然后往文件夹里添加STZhongsong.ttf文件，用TeXworks editor打开main文件，进行编译，并未修改源代码，





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangyxi/WHUT-Bachelor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huangyxi/WHUT-Bachelor] 学长，请问为什么把字体加进项目文件后，还是无法显示华文中宋字体啊。 (Issue #4)





 
虽然系统版本原因的可能性极小，而且在系统升级前我也能正常输出华文中宋字体，不过由于我手边没有Windows 10的设备，当然也不能排除这个原因。
 但是我还是希望阁下能提供更多能复现该问题的信息，也就是issue提交模板即阁下发的信息中推荐提交的6个部分。
 关键是阁下是从clone或下载，到输出最终文件一共经过了哪些（关键）操作，例如是否有按照README文件和回复引用提及的重命名字体文件名，修改了源文件哪些代码，最小能复现问题的代码（Minimum Working Example，MWE）等等。

**Comment by huangyxi** [comment]
阁下是如何通过什么软件（或人眼）判定封面上的部分字体不是华文中宋的呢？

**Comment by nonholonomic** [comment]
感觉比第二个字体要细一点。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangyxi/WHUT-Bachelor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huangyxi/WHUT-Bachelor] 学长，请问为什么把字体加进项目文件后，还是无法显示华文中宋字体啊。 (Issue #4)





 
阁下是如何通过什么软件（或人眼）判定封面上的部分字体不是华文中宋的呢？

**Comment by huangyxi** [comment]
第二个字体是哪个字体？在哪里的字体？可以截个图吗？我在[第一个回复](https://github.com/huangyxi/WHUT-Bachelor/issues/4#issuecomment-1101956791)已经提及了其中一种软件检查字体的方法，如果阁下不方便，也可以通过搜索引擎查询其他的使用软件检查PDF文件中字体的方法。

另外推荐学习一下[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
