### ISSUE TITLE
模板导出的文献格式中似乎存在不必要的"//"符号问题

### ISSUE THREAD

**Issue by JYH1999** [huangyxi/WHUT-Bachelor#5]
模板导出的文献格式中存在不必要的"//"符号，使用以下链接中的解决方法能够解决此问题。
https://blog.csdn.net/weixin_41951986/article/details/117385037
按照此链接修改whut-bachelor.cls中的第81行可以解决，修改内容为：
\RequirePackage[backend=biber,style=numeric,sorting=none,gbpub=false,bibstyle=gb7714-2015,citestyle=gb7714-2015,
gbpunctin=false]{biblatex}

**Comment by huangyxi** [comment]
阁下您好，感谢提出有关参考文献的issue，以及提供相应解决方案。

国家标准GB/T 7714-2015《信息与文献 参考文献著录规则》（以下简称“最新标准”）是自2015-12-01开始实施，目前（2022-4-20）仍然生效的最新标准。根据最新标准，参考文献中使用“//”是符合规范的“析出文献”，故本模板的该行为不应视作bug。

以下摘录部分最新标准：
> 8 著录细则
> 8.8 析出文献
> 8.8.1 从专著中析出有独立著者、独立篇名的文献按4.2 的有关规定著录，其析出文献与源文献的关系用“//”表示。凡是从报刊中析出具有独立著者、独立篇名的文献按4.4的有关规定著录，其析出文献与源文献的关系用“·”表示。关于引文参考文献的著录与标识参见10.1.3与10.2.4 。
>>  示例1：姚中秋. 作为一种制度变迁模式的“转型”[M]//罗卫东, 姚中秋. 中国转型的理论分析：奥地利学派的视角. 杭州: 浙江大学出版社, 2009:44.

即便在最新标准之前实行的，目前已被代替的国家标准GB/T 7714-2005《文后参考文献著录规则》，在以下所摘录的标准中，也有关于“//”析出文献的规范。
> 4 著录项目与著录格式
> 4.2 专著中的析出文献
> 4.2.2 著录格式
> 析出文献主要责任者. 析出文献题名[文献类型标志]. 析出文献其他责任者//专著主要责任者. 专著题名: 其他题名信息. 版本项. 出版地: 出版者, 出版年: 析出文献的页码[引用日期]. 获取和访问路径.

如果阁下以及有相关需求的用户仍然需要删除“析出文献”，可以暂时先手动修改阁下所提及的代码，本人视需求情况决定添加实现阁下所述功能的选项。

声明：上述摘录段落著作权归属原著作权人。摘录依据《著作权法》第二章第四节第二十四条：
> 在下列情况下使用作品，可以不经著作权人许可，不向其支付报酬，但应当指明作者姓名或者名称、作品名称，并且不得影响该作品的正常使用，也不得不合理地损害著作权人的合法权益：（六）**为学校课堂教学或者科学研究，翻译、改编、汇编、播放或者少量复制已经发表的作品，供教学或者科研人员使用，但不得出版发行。**

**Comment by JYH1999** [comment]
非常感谢学长的回答，受教了
