### ISSUE TITLE
请问行间距好像不一样如何解决

### ISSUE THREAD

**Issue by zichuan-liu** [huangyxi/WHUT-Bachelor#6]
我看和word版本还是有些许差异，与曹宇版本的latex也有差异，比如行间距或者字体的感觉，对之后答辩和提交是否有影响，18级有人拿这个做毕设吗。谢谢！

**Comment by huangyxi** [comment]
感谢阁下的提问，以下针对阁下提出的系列问题分别解答。

1. 行间距问题：
    根据2020年的《武汉理工大学本科生毕业设计（论文）撰写规范》（也就是本人自己实际使用模板那年的规范，以下简称《规范》），全文“行距”或“行间距”一词的相关段落仅出现一次， 即“标题以外的文字行距为‘固定值’20磅”。本模板通过文档类文件[`whut-bachelor.cls`](../blob/master/whut-bachelor.cls)中的[`\setlength{\baselineskip}{20pt}`](../blob/bccdc086bcb05a44b30f87a4590d88ef1c95ed5d/whut-bachelor.cls#L110)实现了《规范》的上述要求。另外，如果《规范》有更新可以另外提出来。

2. 字体问题：
    根据[`README.md`](../blob/master/README.md)文件中的[编译环境要求](../blob/bccdc086bcb05a44b30f87a4590d88ef1c95ed5d/README.md?plain=1#L3-L7)，当前模板仅支持Windows系统，且是在本人能力范围内尽可能实现《规范》的要求。如果在其他操作系统使用本模板的过程中，有如默认字体与规范要求不一致等不符合预期的行为，欢迎提出pull request。

3. 对答辩和提交是否有影响：
    具体情况具体分析。本人当年（2021年提交论文）使用的本模板，对答辩和提交没有任何（负面）影响，但实际对阁下是否有影响取决于指导老师、学院要求、个人LaTeX能力、包括对法律/著作权敬畏程度（775269512/WHUT_CUMCM20#3）等因素。

4. 2018级是否有使用者基于本模板完成毕业设计：
    2018级使用者尚不清楚，不过根据合理推测，2021年答辩结束以后，在本模板下提出issue的使用者至少是2018级的，如果阁下有需要可以自行询问确认。不过根据可靠信息来源，本人（2017级）以及至少一位2016级使用者使用本模板完成毕业设计流程。

**Comment by zichuan-liu** [comment]
学长您好，感谢您详尽的回复，目前问题已解决。您所提到的whutmod.cls已删除。

**Comment by huangyxi** [comment]
本项目相关内容讨论已结束。
