### ISSUE TITLE
有关向文档中添加附录的问题

### ISSUE THREAD

**Issue by JYH1999** [huangyxi/WHUT-Bachelor#7]
学长你好，想问一下本模板如何在论文末尾添加附录呢？
我注意到body目录下有示例文件appendices.tex，但如果直接在main.tex下include该文件会报Undefined control sequence错误。按照网上通用的方法在main.tex开头添加\usepackage{appendix}语句后，报错依然存在。
麻烦学长指点，不胜感激！

**Comment by huangyxi** [comment]
阁下您好，感谢反馈关于附录的问题。

已明确该行为是由于未导出到模板 `WHUT-Bachelor` 的自用宏包 [`tikz`](https://tikz.net/) 和其库 `external` 的相关指令残留引起的。现已移除残留指令。

自版本 `v0.9999` 以后，如阁下需要使用附录结构，不引入 `appendix` 宏包，可以直接在 [`main.tex`](../blob/master/main.tex) 中使用
```tex
\include{body/appendices}
```
在 [`body/appendices.tex`](../blob/master/body/appendices.tex) 文件 `\appendix` 指令之后的章节（`\section`）编号将转换为附录编号。

**Comment by JYH1999** [comment]
非常感谢学长的解答！

**Comment by JYH1999** [comment]
学长您好，我使用更新后的模板，按照您给出的方法进行了附录添加，但编译生成的附录格式似乎存在一些问题。
我注意到学校的论文格式文件中，对附录的格式定义是这样的：
（20）附录
论文附录依次用大写字母“附录A、附录B、附录C……”表示，附录内的分级序号可采用“附A1、附A1.1、附A1.1.1”等表示，图、表、公式均依此类推为“图A1、表A1、式（A1）”等。

同样地，我在学长的模板文件中找到下列可能相关的代码：
`%% redefine appendix
\let\@appendix\appendix
\renewcommand\appendix{\par
	\@appendix
	\gdef\thesection{\appendixname\@Alph\c@section}
	\gdef\thesubsection{\Alph{section}.\@arabic\c@subsection}
	\gdef\thesubsubsection{\Alph{section}.\arabic{subsection}.\@arabic\c@subsubsection}
	% \ifwhut@options@minimal\else\tikzexternaldisable\fi
	\let\@appendix\relex
}`
看上去学长似乎确实想要使模板生成的附录格式与学校规范文件要求的格式“附录A 附录B...”相同，但在编译后的PDF文档中，附录的格式如下所示：
A 附录标题
我的编译环境是Windows11+TexLive2022+TexStudio，应该与学长的测试环境相同。所以这里可能是一个bug嘛？

**Comment by huangyxi** [comment]
已于分支 [`issue7-appendix`](../tree/issue7-appendix) 修复上述问题，待确认无误后并入主分支。

另外有关规范文件还有一点要向阁下咨询一下，规范在“毕业设计（论文）内容：目录”、“撰写要求：字体和字号”等多个环节只提及三级标题，然而在“附录”中疑似出现“附A1.1.1”的四级标题。为了解释这个出现的四级标题，想问一下例如“附录B第二节第一子节”是表示为以下哪种标题：

1. `附B2.1` “四级标题”为规范笔误，或仅在正文中出现而不在目录中出现
2. `附A2.2.1` 将“A”解释为与“附”连接在一起的符号
3. `附B.2.1` 将拉丁字母后的数字解释为多余字符予以删除
4. `其他情况` 本人对规范理解有偏差

还望解答，以便在模板中实现相应规范要求。

**Comment by JYH1999** [comment]
学长好，我使用分支中的模板添加了附录，目前没有发现我能察觉到的问题，非常感谢学长对模板的改进！
关于学长提及的四级标题问题：我也注意到了规范文件中存在学长所述的模糊要求，但由于本人的附录结构深度原因没有特别加以关注。学长提及后我向指导老师进行了相关咨询，但没有得到确定的回答（可能老师自己也没有意识到）。就我个人的理解来看，我倾向于选择学长所述的第1种方案，即四级标题仅在附录正文中出现，目录中不出现，但个人见解仅供学长参考。
最后，再次感谢学长对模板的付出！

**Comment by huangyxi** [comment]
感谢使用本模板，本问题讨论已结束，如果有新的问题欢迎新开issue。
