### ISSUE TITLE
关于在Linux上使用SimSun字体的问题

### ISSUE THREAD

**Issue by hr567** [huangyxi/WHUT-Bachelor#8]
### 系统环境
Ubuntu 22.04 on WSL

### 问题说明
当在Ubuntu中安装了Windows的SimSun字体且启用heitipatch后，由于[cls第64行](https://github.com/huangyxi/WHUT-Bachelor/blob/ee6a2ff4630d65e2ea5f243fbc011ef9a229ac28/whut-bachelor.cls#L64)中的设置，使用的斜体字名称为SimKai，此时无法编译文档，错误为无法查找到SimKai匹配字体。

### 解决方案
通过将SimKai改为KaiTi能够正确匹配simkai.ttf字体。由于我没有Windows下Texlive环境，所以不清楚该修改能否用于Windows。

_（附：作者我的超人，谢谢大佬的模板 👍_

**Comment by huangyxi** [comment]
感谢阁下提出问题和对应解决方案。

由于支持新的编译环境需要测试的项目比较多，本人近期闲暇时间也比较有限，如果按照阁下所提及的方案可以解决所述问题，还请阁下暂时手动修改对应代码。

**Comment by huangyxi** [comment]
抱歉长时间没有响应，感谢阁下提供的修正方案，本人已经将相关PR合并。

但由于无法测试多平台兼容性，暂时将PR合并至分支 [issue8-fonts](https://github.com/huangyxi/WHUT-Bachelor/tree/issue8-fonts)，待有机会测试多平台后合并至主分支。
